### ISSUE TITLE
> Where 's all the documentation?

### ISSUE THREAD

**Issue by milongkmt** [rbenv/ruby-build#1833]
> Where 's all the documentation?
<br/>

I'm trying to use include to get data in a yaml file that's related to a list item in my template. But I just get `Liquid.ArgumentError: Illegal template name my-item-file.yaml`

**For example**

```html
<!-- component.html -->
<ul>
  {% for item in items %}
  {% include {{item.slug}} %}
  <li>
    <h1>{{ include.title }}</h1>
    <img src="{{ include.thumbnail }}" alt="{{ include.description }}" />
  </li>
  {% endfor %}
</ul>
```

```yaml
# data.yaml
items:
  - slug: file-1.yaml
  - slug: file-2.yaml
```

```yaml
# file-1.yaml
tile: File 1 Title
thumbnail: http://thumbnail-image-path
description: Thumbnail description
```

```js
// engine.js
const engine = new liquid.Engine();
engine.registerFileSystem(new liquid.LocalFileSystem("./", "yaml"))

async function liquify(component, data) {
  const template = await engine.parse(component);
  const result = await template.render(data);
  return result;
}
```

__Originally posted by @mudlabs in https://github.com/docs/liquid/issues/121__
